miApp/config/routes.rb
MiApp::Application.routes.draw do
  get "usuario_tipos/txt"

  resources :menu_usuario_tipos

  resources :usuarios

  resources :menus

  resources :usuario_tipos

  resources :comentarios

  get "home/index"

  get "home/acerca_de"

  get "home/cambio_clave"

  get "home/ingreso"

  get "home/cambio_clave"

  get "home/acceso_denegado"

  get "home/salir"

  post "home/ingresar"

  post "home/cambiar_clave"

  root :to => 'home#index'

end

miApp/app/models/usuario.rb
class Usuario < ActiveRecord::Base

  validate :clave_valida

  validates_uniqueness_of :login, :message => 'existe en la base de datos'
  validates_presence_of   :login, :nombre, :clave, :message => 'no puede estar vacio'
  validates_length_of     :login, :within => 3..20, :message => 'debe tener entre 3 y 20 caracteres'
  validates_format_of     :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => 'incorrecto'

  def clave_valida
    if self.clave.size < 6
      errors.add(:clave, 'debe debe tener al menos 6 caracteres')
    end
  end

  # Relacion con tablas
  belongs_to :usuario_tipo

end

miApp/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

  before_filter :access_menu

  def index
    @usuarios = Usuario.all
  end

  def show
    @usuario = Usuario.find(params[:id])
  end

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(params[:usuario])

    if @usuario.save
      render action: "show", notice: 'Registro creado.'
    else
      render action: "new"
    end
  end

  def edit
    @usuario = Usuario.find(params[:id])
  end

  def update
    @usuario = Usuario.find(params[:id])

    if @usuario.update_attributes(params[:usuario])
      render action: "show", notice: 'Registro actualizado.'
    else
      render action: "edit"
    end
  end

  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy
    redirect_to usuarios_url
  end

end

miApp/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

miApp/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>

  <% if @usuario.errors.any? %>
  <div>
      <h3> <%= image_tag('error.gif') %> El registro no se puede guardar:
      </h3>
      
      <ul>
        <% @usuario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
  <% end %>

  <pre>
  <%= f.label 'Login:       ' %> <%= f.text_field :login %>
  <%= f.label 'Nombre:      ' %> <%= f.text_field :nombre %>
  <%= f.label 'e-Mail:      ' %> <%= f.text_field :email %>
  <%= f.label 'Tipo Usuario:' %> <%= f.collection_select(:usuario_tipo_id, UsuarioTipo.all, :id, :nombre) %>
  <%= f.label 'Clave:       ' %> <%= f.text_field :clave %></pre>

  <%= f.submit 'Guardar' %> <br /> <br />

<% end %>

miApp/app/views/usuarios/edit.html.erb
<h2>Editar Usuario</h2>

<%= render 'form' %>

<%= link_to image_tag('volver.gif'), usuarios_path %>

miApp/app/views/usuarios/index.html.erb
<h2><%= link_to image_tag('usuario.png') %> Usuarios</h2>

<table class='webgrid'>
  <tr class='webgrid-header'>
	<th>ID</th>
    <th>Login</th>
    <th>Nombre</th>
    <th>Tipo</th>
    <th>Creado</th>
    <th>Modificado</th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |registro| %>
  <tr class='webgrid-row-style'>
	<td><%= registro.id %></td>
	<td><%= registro.login %></td>
    <td><%= registro.nombre %></td>
    <td><%= registro.usuario_tipo.nombre %></td>
    <td><%= ver_fecha_df(registro.created_at) %></td>
    <td><%= ver_fecha_df(registro.updated_at) %></td>
    <td><%= link_to image_tag('edit.gif'),   edit_usuario_path(registro) %></td>
    <td><%= link_to image_tag('delete.gif'), registro, confirm: 'Esta Seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to image_tag('crear.gif'), new_usuario_path %>

miApp/app/views/usuarios/new.html.erb
<h2>Nuevo Usuario</h2>

<%= render 'form' %>

<%= link_to image_tag('volver.gif'), usuarios_path %>

miApp/app/views/usuarios/show.html.erb
<h3>
	<%= image_tag('ok.gif') %>
	<%= notice %>
</h3>

<p>
	<b>Usuario:</b>
	<%= @usuario.login + ' (' + @usuario.nombre + ')' %>
</p>

<%= link_to image_tag('volver.gif'), usuarios_path %>